### PR TITLE
Adds Events part 1.

### PR DESCRIPTION
**Pull request by jmeas**
This is the first part of a 2-part post to respond to [this blog post](http://naturaily.com/blog/post/marionette-plain-object-over-reqres-commands-above-all)

### CODE REVIEW

**Comment by samccone** [comment]
ping ping @jmeas

**Comment by samccone** [comment]
@jmeas 
> I already started on a response to another anti-reqres blog. I'm not that interested in spending time content on our blog til it's a little better :(

Can you expand on 
> I'm not that interested in spending time content on our blog til it's a little better :(

What does this mean? What needs to be better? Can you open issues for what needs to be better for you to justify sharing knowledge?

**Comment by jdaudier** [comment]
ref https://github.com/marionettejs/blog/issues/14

**Comment by jmeas** [comment]
Gonna close and write a better one

**Comment by samccone** [comment]
kk :heart:

**Pull request closed without merging**
